sudo: required
dist: trusty
language: c
before_install: sudo apt-get install -qq php5
addons:
 apt:
   sources:
   - ubuntu-toolchain-r-test
   packages:
   - gcc-4.8
   - g++-4.8
script:
   - cmake .
   - make VERBOSE=1
   - php tests/test.php
env:
   global: CXX=g++-4.8
