sudo: required
dist: trusty
language: c
python:
    - "2.7"
addons:
 apt:
   sources:
   - ubuntu-toolchain-r-test
   packages:
   - gcc-4.8
   - g++-4.8
   - python
   - xsltproc
script:
   - cmake .
   - make VERBOSE=1
   - php tests/test.php
env:
   global: CXX=g++-4.8
