sudo: required
dist: trusty
language: c
python:
    - "2.7"
addons:
 apt:
   sources:
   - ubuntu-toolchain-r-test
   packages:
   - gcc-4.8
   - g++-4.8
   - xsltproc
   - python-pip
install:
   - pip install fire
script:
   - cmake .
   - make VERBOSE=1
   - tests/test_output.py
   - tests/test_commands.py
env:
   global: CXX=g++-4.8
